estudiantes = [
    {"nombre": "Fernando", "edad": 31, "ocupacion": "Ingeniero", "sexo":"Masculino"},
    {"nombre": "Lucía", "edad": 25, "ocupacion": "Diseñadora", "sexo": "Femenino"},
    {"nombre": "Adrián", "edad": 42, "ocupacion": "Chef", "sexo": "Masculino"},
    {"nombre": "Martina", "edad": 28, "ocupacion": "Periodista", "sexo": "Femenino"},
    {"nombre": "Mateo", "edad": 35, "ocupacion": "Arquitecto", "sexo": "Masculino"},
    {"nombre": "Elena", "edad": 19, "ocupacion": "Estudiante", "sexo": "Femenino"},
    {"nombre": "Sam", "edad": 30, "ocupacion": "Programador", "sexo": "No binario"},
    {"nombre": "Valeria", "edad": 22, "ocupacion": "Fotógrafa", "sexo": "Femenino"},
    {"nombre": "Julián", "edad": 54, "ocupacion": "Contador", "sexo": "Masculino"},
    {"nombre": "Camila", "edad": 29, "ocupacion": "Marketing", "sexo": "Femenino"},
    {"nombre": "Roberto", "edad": 61, "ocupacion": "Jubilado", "sexo": "Masculino"},
    {"nombre": "Sofía", "edad": 33, "ocupacion": "Abogada", "sexo": "Femenino"},
    {"nombre": "Dante", "edad": 27, "ocupacion": "Músico", "sexo": "Masculino"},
    {"nombre": "Alex", "edad": 24, "ocupacion": "Analista de Datos", "sexo": "No binario"},
    {"nombre": "Beatriz", "edad": 45, "ocupacion": "Doctora", "sexo": "Femenino"},
    {"nombre": "Hugo", "edad": 38, "ocupacion": "Carpintero", "sexo": "Masculino"},
    {"nombre": "Paola", "edad": 31, "ocupacion": "Veterinaria", "sexo": "Femenino"},
    {"nombre": "Isabel", "edad": 47, "ocupacion": "Psicóloga", "sexo": "Femenino"},
    {"nombre": "Ricardo", "edad": 36, "ocupacion": "Electricista", "sexo": "Masculino"},
    {"nombre": "Mariana", "edad": 23, "ocupacion": "Influencer", "sexo": "Femenino"},
    {"nombre": "Gabriel", "edad": 50, "ocupacion": "Gerente", "sexo": "Masculino"},
    {"nombre": "Daniela", "edad": 26, "ocupacion": "Científica", "sexo": "Femenino"},
    {"nombre": "Tomás", "edad": 41, "ocupacion": "Conductor", "sexo": "Masculino"},
    {"nombre": "Sara", "edad": 34, "ocupacion": "Traductora", "sexo": "Femenino"},
    {"nombre": "Leo", "edad": 21, "ocupacion": "Barista", "sexo": "No binario"},
    {"nombre": "Fernando", "edad": 29, "ocupacion": "Fisioterapeuta", "sexo": "Masculino"},
    {"nombre": "Clara", "edad": 58, "ocupacion": "Profesora", "sexo": "Femenino"},
    {"nombre": "Joaquín", "edad": 32, "ocupacion": "Chef de Partie", "sexo": "Masculino"},
    {"nombre": "Mónica", "edad": 44, "ocupacion": "Enfermera", "sexo": "Femenino"},
    {"nombre": "Esteban", "edad": 27, "ocupacion": "Diseñador UX", "sexo": "Masculino"},
    {"nombre": "Victoria", "edad": 39, "ocupacion": "Escritora", "sexo": "Femenino"},
    {"nombre": "Oscar", "edad": 52, "ocupacion": "Mecánico", "sexo": "Masculino"},
    {"nombre": "Natalia", "edad": 30, "ocupacion": "Analista Financiero", "sexo": "Femenino"},
    {"nombre": "Bruno", "edad": 25, "ocupacion": "Entrenador", "sexo": "Masculino"},
    {"nombre": "Andrea", "edad": 48, "ocupacion": "Arquitecta", "sexo": "Femenino"},
    {"nombre": "Felipe", "edad": 37, "ocupacion": "Project Manager", "sexo": "Masculino"},
    {"nombre": "Luna", "edad": 22, "ocupacion": "Estudiante de Arte", "sexo": "No binario"},
    {"nombre": "Luna", "edad": 22, "ocupacion": "Estudiante de Arte", "sexo": "No binario"},
    {"nombre": "Carlos", "edad": None, "ocupacion": "Ingeniero", "sexo": "Masculino"},
    {"nombre": "Sofía", "edad": 28, "ocupacion": None, "sexo": "Femenino"},
    {"nombre": "Mateo", "edad": 35, "ocupacion": "Chef"}, 
    {},
    {"nombre": None, "edad": None, "ocupacion": None, "sexo": None},
    {"nombre": "Valeria", "edad": "veinticinco", "ocupacion": "Diseñadora", "sexo": "Femenino"},
    {"nombre": "Erik", "edad": 40, "ocupacion": "Carpintero", "sexo": None},
    {"nombre": "Maya", "ocupacion": "Programadora", "sexo": "No binario"},
    {"nombre": "Liam", "edad": 19, "ocupacion": "Músico", "sexo": "Masculino"},
    {"nombre": "Sara", "edad": None, "ocupacion": "Doctora", "sexo": "Femenino"},
    {},
    {"nombre": "Julián", "edad": 31, "ocupacion": "Analista", "sexo": None},
    {"nombre": None, "edad": 45, "ocupacion": "Profesor", "sexo": "Masculino"},
    {"nombre": "Elena", "edad": 0, "ocupacion": "Desempleada", "sexo": "Femenino"},
    {"nombre": "Tomas", "ocupacion": "Escritor"},
    {"nombre": "Olivia", "edad": 27, "ocupacion": "", "sexo": "No binario"},
    {"nombre": "Lucas", "edad": -1, "ocupacion": "Estudiante", "sexo": "Masculino"},
    {"nombre": "Nina", "edad": 22, "ocupacion": "Artista", "sexo": "Otro"},
    {},
    {"nombre": "Marcos", "edad": 50, "ocupacion": None, "sexo": "Masculino"},
    {"nombres": "Error de Clave", "edad": 30, "ocupacion": "Tester", "sexo": "Femenino"},
    {"nombre": " ", "edad": 25, "ocupacion": "Ventas", "sexo": "Masculino"},
    {"nombre": "Dante", "edad": None, "ocupacion": None, "sexo": None},
    {"nombre": "Clara", "edad": "33 años", "ocupacion": "Arquitecta", "sexo": "Femenino"},
    {"nombre": "Bruno", "edad": 29, "ocupacion": "Mecánico"},
    {"nombre": "Sonia", "edad": 41, "ocupacion": "Abogada", "sexo": "Femenino"},
    {},
    {"nombre": "Ivan", "edad": 18, "ocupacion": "N/A", "sexo": "Masculino"},
    {"nombre": "Gaby", "edad": None, "ocupacion": "Científica", "sexo": "Femenino"},
    {"nombre": "Felix", "edad": 37, "ocupacion": "Cocinero", "sexo": "Masculino"},
    {"nombre": "Rosa", "edad": 60, "ocupacion": "Jubilada", "sexo": "Femenino"}
]